sources:
  - name: src 
    database: sourcedb
    schema: mkmall
    tables:
      
      - name: regions
        description: Raw data of region info

      - name: nations 

      - name: customers

      - name: suppliers

      - name: lineitems

      - name: orders
        config:
          freshness:
            warn_after: {count: 6, period: day}
            # warn_after: {count: 153, period: day}
            error_after: {count: 153, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz
        


